### ISSUE TITLE
Installation Error upon Package AutoDiscovery 

### ISSUE THREAD

**Issue by stelgenhof** [RoyVoetman/laravel-gitlab-storage#3]
When Laravel is running its step of auto discovery, the installation fails:

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Argument 2 passed to RoyVoetman\FlysystemGitlab\Client::__construct() must be of the type string, null given, called in ../vendor/royvoetman/laravel-gitlab-storage/src/GitlabStorageServiceProvider.php on line 24

  at vendor/royvoetman/flysystem-gitlab-storage/src/Client.php:45
    41|      * @param  string  $projectId
    42|      * @param  string  $branch
    43|      * @param  string  $baseUrl
    44|      */
  > 45|     public function __construct(string $personalAccessToken, string $projectId, string $branch, string $baseUrl)
    46|     {
    47|         $this->personalAccessToken = $personalAccessToken;
    48|         $this->projectId = $projectId;
    49|         $this->branch = $branch;
```

This happens on a new project, likely caused by the fact that the configuration hasn't been defined yet.

**Comment by RoyVoetman** [comment]
I tried to replicate your issue with Laravel (v7.2.2) and I didn't encounter this error. This package isn't using a self-provided configuration file, it purely uses the "disks" section in the filesystems.php file provided by Laravel itself.

It is known that on instantiation of the disk with: `Storage::disk('gitlab')` it will return this error if you haven't specified your project id (`GITLAB_PROJECT_ID`) in the .env file (it defaults to `null`). This should however never happen on package discovery because disks are not instantiated on package discovery. 

Which version of Laravel are you using? 
And could you include your composer.json file?

**Comment by stelgenhof** [comment]
I'm also using Laravel 7.2.2. Anyway, never mind, I can't really replicate this in another environment. Sorry for the trouble!
